### ISSUE TITLE
ModuleNotFoundError: No module named 'gsnet'

### ISSUE THREAD

**Issue by troyehuang** [R-PMArt/rpmart#1]
Hi, i meet this error when i tried to run real_service.py by following the instruction.
did i miss something? hope you can help me fix the problem.
thank you very much!

encoder.load_state_dict(torch.load(f'{trained_path}/weights/encoder_latest.pth', map_location=torch.device('cuda')))
===> loaded roartnet 1.9277136325836182
===> loading graspnet
Traceback (most recent call last):
  File "real_service.py", line 118, in <module>
    from gsnet import AnyGrasp
ModuleNotFoundError: No module named 'gsnet'

**Comment by dadadadawjb** [comment]
Hi,

Have you followed the instructions in [AnyGrasp](https://github.com/graspnet/anygrasp_sdk) to download the license, weights and binary codes? There should exist `gsnet.so` in the root directory so that you can import it.

Hope this helps!
